
BaseURL = "/"
languageCode = "en-us"
title = "Ratio Engineering"

themesDir = "../.."

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]

  [params.logo]
    mobile = "images/ratiologo.svg"
    mobile_height = "29px"
    mobile_width = "217px"
    desktop = "images/ratiologo.svg" 
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Hugo Hero"

  [params.homepage_meta_tags]
    meta_description = "Systems Engineering Services."
    meta_og_title = "Ratio Engineering Aps"
    meta_og_type = "website"
    meta_og_url = "https://www.ratio-engineering.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Systems Engineering Services."
    #meta_twitter_card = "summary"
    #meta_twitter_site = "@zerostaticio"
    #meta_twitter_creator = "@zerostaticio"



[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3


[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
